# Copied from cabal: https://raw.githubusercontent.com/haskell/cabal/master/appveyor.yml
# Use ghc 7.8.3 to reproduce https://github.com/feuerbach/ansi-terminal/issues/22
install:
  # Using '-y' and 'refreshenv' as a workaround to:
  # https://github.com/haskell/cabal/issues/3687
  - choco install -y ghc --version 7.8.3
  - refreshenv
  # See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found#comment_42195491
  # NB: Do this after refreshenv, otherwise it will be clobbered!
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - cabal --version
  - cabal update

build_script:
  - cabal build
